  language: python
  python:
    - 3.6
    - nightly
# command to install dependencies
  install:
    - pip install -r requirements.txt
  script:
    - python -m unittest -v tests.py
  notifications:
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

